---
title: "MGIS.FW_LUC.Xwalk_Comparison"
format: html
editor: visual
---

# 0.0 Environment Set-up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Loads libraries from LPDB_libraries.R script
source(here::here("03_Scripts/LPDB_libraries.R"))

# Load functions from LPDB_functions.R script
source(here::here("03_Scripts/LPDB_functions.R"))

# Load data keys to crosswalk municipality names to municipal IDs
keys <- mapcdatakeys::all_muni_data_keys |> 
  select(c(muni_name,muni_id)) |> 
  mutate(muni_name = stringr::str_to_title(muni_name))

#Global options to remove scientific notation and set random seed
options(scipen = 999)
set.seed(351)

# Set Land Use Code Vintage
q <- "Q1"
yr <- "2026"
```

# 1.1 Load MAPC Land Use Code Crosswalk
```{r}
# Load the MAPC Land Use Code Crosswalk
mapc.luc.xwalk <- readRDS(here(paste0("04_Output/Internal/MAPC.LUC_xwalk_.",q,"_",yr,".rds")))
```

# 1.2 Load Complementary Datasets
```{r}
# Load MHP Residensity product Land Use Codes
# File download from
# Create a one digit land use code flag and remove TOWN_ID == 0 (DLS Standard Codes)
mhp.luc.xwalk <- read_xlsx(here("02_Data/Raw/Land Use Codes/MHP/LUTstandards_Residensity.xlsx"), sheet = 1) |>
  mutate(od_uc = str_sub(USE_CODE, start = 1, end = 1)) |> filter(TOWN_ID != 0) |> 
  left_join(keys, c("TOWN_ID" = "muni_id"))
# 
# Load UMDI Land Use Code Crosswalk
# File download from 
umdi.luc.xwalk <- read_xlsx(here("02_Data/Raw/Land Use Codes/UMDI/Standardized LUC Matching Guide_ForDistribution20260428.xlsx"), sheet = 1) |>
  mutate(od_uc = str_sub(USE_CODE, start = 1, end = 1))

```

# 2.0 MAPC Land Use Code Crosswalk Validation + QA/QC
# 2.1 UMDI Land Use Code Crosswalk Comparison
```{r}
# UMDI Individual Analysis
# Number of Unique Land Use Codes
tbl.1.umdi <- umdi.luc.xwalk |> 
  group_by(STD_LUC) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()
# 98 standard Land use codes contained in the 

# What "Broad use" categories are defined?
tbl.2.umdi <- umdi.luc.xwalk |> 
  group_by(CATEGORY) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()
# 7 broad use categories definiting the standard land use codes contained in the crosswalk.

########
# UMDI Comparison Analysis
umdi.comp <-
  left_join(
    mapc.luc.xwalk,
    umdi.luc.xwalk,
    by = c("MUNI.USE_CODE" = "USE_CODE", "MUNI.USE_DESC" = "USE_DESC")
  ) |> 
  mutate(
     std.luc_compare = if_else(STD.USE_CODE == STD_LUC, TRUE, FALSE),
     std.luc_comp_compare = if_else(STD.USE_CODE == STD_LUC, TRUE, FALSE),
  )

###
# Tables looking at the distribution of land use codes by 
# - Whether the initial matched land use code/text analyzed assigned code/mixed use assigned code matches to the UMDI code or the text analysis/mixed use assigned code matches to the UMDI code
# Comparison of initial matched land use code/text analyzed assigned code/mixed use assigned code matches to the UMDI code
umdi_std.1stcomp_tbl <- umdi.comp |>
  group_by(std.luc_compare) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()
# Comparison of text analysis/mixed use assigned code matches to the UMDI code
umdi_std.2ndcomp_tbl <- umdi.comp |>
  group_by(std.luc_comp_compare) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()

# Comparison of both
umdi_std.1st2ndcomp_tbl <- umdi.comp |>
  group_by(std.luc_compare, std.luc_comp_compare) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()
###

####
# Tables looking at the distribution of land use codes based on:
# - Whether they matched to a standard use code initially
# - Whether the initial matched land use code/text analyzed assigned code/mixed use assigned code matches to the UMDI code or the text analysis/mixed use assigned code matches to the UMDI code

# Comparison of initial matched land use code/text analyzed assigned code/mixed use assigned code matches to the UMDI code
initial.match_1stcomp_tbl <- umdi.comp |>
  group_by(matched, std.luc_compare) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()
# Comparison of text analysis/mixed use assigned code matches to the UMDI code
initial.match_2ndcomp_tbl <- umdi.comp |>
  group_by(matched, std.luc_comp_compare) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()
####

####
# Tables looking at the distribution of land use codes based on:
# - One Digit Use Code category
# - Whether the initial matched land use code/text analyzed assigned code/mixed use assigned code matches to the UMDI code or the text analysis/mixed use assigned code matches to the UMDI code

# Comparison of initial matched land use code/text analyzed assigned code/mixed use assigned code matches to the UMDI code
od.uc_1stcomp_tbl <- umdi.comp |>
  group_by(od_uc, std.luc_compare) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()
# Comparison of text analysis/mixed use assigned code matches to the UMDI code
od.uc_2ndcomp_tbl <- umdi.comp |>
  group_by(od_uc, std.luc_comp_compare) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()
####

# Write data tables
write.csv(umdi.comp, here(paste0("02_Data/Logs/Use Code Comparison Table Diagnostics/UMDI/UMDI.comp.csv")), row.names = FALSE)
write.csv(umdi_std.1stcomp_tbl, here(paste0("02_Data/Logs/Use Code Comparison Table Diagnostics/UMDI/UMDI.code.comp_tbl.csv")), row.names = FALSE)
write.csv(initial.match_1stcomp_tbl, here(paste0("02_Data/Logs/Use Code Comparison Table Diagnostics/UMDI/UMDI.initialmatch.comp_tbl.csv")), row.names = FALSE)
write.csv(od.uc_1stcomp_tbl, here(paste0("02_Data/Logs/Use Code Comparison Table Diagnostics/UMDI/UMDI.oduc.comp_tbl.csv")), row.names = FALSE)

# Full set of land use codes 
umdi.f_matched_std.luc_compare <- umdi.comp |> filter(matched == 1 & std.luc_compare == FALSE) |> 
  select(MUNI.USE_CODE, MUNI.USE_DESC, STD.USE_CODE, STD.USE_DESC, STD.USE_CODE_comp, STD_LUC, CATEGORY, od_uc)
umdi.f_unmatched_std.luc_compare <- umdi.comp |> filter(matched == 0 & std.luc_compare == FALSE)|> 
  select(MUNI.USE_CODE, MUNI.USE_DESC, STD.USE_CODE, STD.USE_DESC, STD.USE_CODE_comp, STD_LUC, CATEGORY, od_uc)

umdi.t_matched_std.luc_compare <- umdi.comp |> filter(matched == 1 & std.luc_compare == TRUE)|> 
  select(MUNI.USE_CODE, MUNI.USE_DESC, STD.USE_CODE, STD.USE_DESC, STD.USE_CODE_comp, STD_LUC, CATEGORY, od_uc)
umdi.t_unmatched_std.luc_compare <- umdi.comp |> filter(matched == 0 & std.luc_compare == TRUE)|> 
  select(MUNI.USE_CODE, MUNI.USE_DESC, STD.USE_CODE, STD.USE_DESC, STD.USE_CODE_comp, STD_LUC, CATEGORY, od_uc)

# Observations
# UMDI does not include a TOWN_ID or municipal name variable making it difficult to crosswalk MAPC's Land Use Code Crosswalk specifically to each Use Code.
# Retains a mix of three and four digit standard codes.
# 
```

# 2.2 MHP Land Use Code Crosswalk Comparison
```{r}
# MHP Individual Analysis
# What are the standardized land use descriptions assigned in the crosswalk?
tbl.1.mhp <- mhp.luc.xwalk |> 
  group_by(standardized_LU_Description) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()
# Residential and Mixed use Codes. Does not include codes outside of that. Only 40 distinct codes. 
# 21 distinct residential descriptions (compared to 19 from DLS)
# 11 distinct mixed use descriptions (compared to 35 different combinations from DLS)

# What are the "BroadUse Categories assigned to each municipal code?
tbl.2.mhp <- mhp.luc.xwalk |> 
  group_by(BroadUse) |> 
  summarise(
    n= n()
  ) |> 
  ungroup()
# 7 "BroadUse" categories which do not all match to the 10 One digit categories from the DLS data. Consolidation of some into broader categories.

mhp.std <- mhp.luc.xwalk |> filter(!is.na(standardized_LUC))

print(nrow(mhp.std))

mhp.no.std <- mhp.luc.xwalk |> filter(is.na(standardized_LUC))

print(nrow(mhp.no.std))

# MHP seems to have created two levels of crosswalking.
# 1) "BroadUse" what I would refer to as the "One-Digit Use Code Category" - 6,553 municipal-specific use codes
# 2) Three digit standardized use codes - 2,385 municipal specific use codes

# Observations
# - Mixed use codes receive a fourth digit suffix "M". I went about operationalizing the text of the DLS Code book - first digit zero, second and third digits representing the two major property classifications (third digit being zero if no other information is provided), and allocating the "_underlying" code to a separate variable to maintain specificity.
# - Unsure what vintage is.
# - Don't address mixed use codes in non-mixed use group + residential.
# - Unclear how consistent the mixed use assignment is/the processes. Instances where 013 is assigned to a parcel that explicitly states its a 037 (comm + ag) (code 137 in town 189)

# MHP Comparison Analysis
mhp.comp <- left_join(
  mapc.luc.xwalk,
  mhp.luc.xwalk,
  by = c("muni_name", "MUNI.USE_CODE" = "USE_CODE")
) |> 
  mutate(
    std.luc_compare = if_else(STD.USE_CODE == standardized_LUC, TRUE, FALSE)
  )

# Dataframe of land use codes not present in MHP Crosswalk.
not.present.mhp <- mhp.comp |> filter(is.na(TOWN_ID))

print(nrow(not.present.mhp))
# 1,611 land use codes present in the Q1 2026 MassGIS Property Tax Parcel file are not present in the MHP crosswalk.

#Dataframe of land use codes no present in the MAPC Crosswalk
not.present.mapc <- mhp.comp |> filter(is.na(MUNI.USE_DESC))
# land use codes present in the MHP Land Use Code crosswalk file are not present in the MAPC Land Use Code Crosswalk.

# Compare the number of crosswalked three digit land use codes which match each other and those that do not.
mhp.std.comp_tbl <- mhp.comp |> 
  filter(!is.na(TOWN_ID)) |>
  filter(!is.na(MUNI.USE_CODE)) |> 
  group_by(std.luc_compare) |> 
  summarise(
    n = n()
  ) |> 
  ungroup()

mhp.f_std.luc_compare <- mhp.comp |> filter(std.luc_compare == FALSE)
mhp.t_std.luc_compare <- mhp.comp |> filter(std.luc_compare == TRUE)

# Takeaways
# MAPC Land Use Code crosswalk has false positives in the three digit standard use code crosswalk. Use codes from municipalities have three digit prefixes which match to DLS standards, but to incorrent codes.

# 

```
